project_id = "qggazjuohdpcualwwkrp"

[functions.create-admin]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.admin-manage-users]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-reset-email]
verify_jwt = false

[functions.send-mass-email]
verify_jwt = false

[functions.vault-api]
verify_jwt = false
